services:
  - docker

install:
  - git clone --quiet --depth 1 https://github.com/mikaelarguedas/ros2ci.git .ros2ci
  - cp additional_repos.repos .ros2ci/

matrix:
  include:
    - env: JOB_TYPE=dashing
      script: .ros2ci/travis.bash $JOB_TYPE
    - env: JOB_TYPE=eloquent
      script: .ros2ci/travis.bash $JOB_TYPE
